[2024-09-15T08:13:45.363+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-15T07:53:41+00:00 [queued]>
[2024-09-15T08:13:45.375+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-15T07:53:41+00:00 [queued]>
[2024-09-15T08:13:45.375+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-15T08:13:45.376+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 6
[2024-09-15T08:13:45.376+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-15T08:13:45.384+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-09-15 07:53:41+00:00
[2024-09-15T08:13:45.388+0000] {standard_task_runner.py:55} INFO - Started process 1789 to run task
[2024-09-15T08:13:45.390+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'save_city_info_weather_v01', 'insert_data', 'manual__2024-09-15T07:53:41+00:00', '--job-id', '350', '--raw', '--subdir', 'DAGS_FOLDER/saver_info.py', '--cfg-path', '/tmp/tmp8lpwry2y']
[2024-09-15T08:13:45.391+0000] {standard_task_runner.py:83} INFO - Job 350: Subtask insert_data
[2024-09-15T08:13:45.424+0000] {task_command.py:389} INFO - Running <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-15T07:53:41+00:00 [running]> on host 0c5fe11d0c9c
[2024-09-15T08:13:45.486+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=save_city_info_weather_v01
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-09-15T07:53:41+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-15T07:53:41+00:00
[2024-09-15T08:13:45.487+0000] {sql.py:253} INFO - Executing: insert into weathers (city_name, max_temp, min_temp, wind, descript)
            values (
                     'Москва',
                     '22.29',
                     '20.24',
                     '3.68',
                     'облачно с прояснениями'); 
[2024-09-15T08:13:45.491+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-15T08:13:45.605+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-15T08:13:45.612+0000] {sql.py:364} INFO - Running statement: insert into weathers (city_name, max_temp, min_temp, wind, descript)
            values (
                     'Москва',
                     '22.29',
                     '20.24',
                     '3.68',
                     'облачно с прояснениями'); , parameters: None
[2024-09-15T08:13:45.613+0000] {sql.py:373} INFO - Rows affected: 1
[2024-09-15T08:13:45.620+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=save_city_info_weather_v01, task_id=insert_data, execution_date=20240915T075341, start_date=20240915T081345, end_date=20240915T081345
[2024-09-15T08:13:45.655+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-09-15T08:13:45.668+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
