[2024-09-15T08:13:44.826+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-15T07:33:25.648343+00:00 [queued]>
[2024-09-15T08:13:44.833+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-15T07:33:25.648343+00:00 [queued]>
[2024-09-15T08:13:44.834+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-15T08:13:44.834+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 6
[2024-09-15T08:13:44.834+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-15T08:13:44.843+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-09-15 07:33:25.648343+00:00
[2024-09-15T08:13:44.847+0000] {standard_task_runner.py:55} INFO - Started process 1787 to run task
[2024-09-15T08:13:44.850+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'save_city_info_weather_v01', 'insert_data', 'manual__2024-09-15T07:33:25.648343+00:00', '--job-id', '348', '--raw', '--subdir', 'DAGS_FOLDER/saver_info.py', '--cfg-path', '/tmp/tmptn6ogvxr']
[2024-09-15T08:13:44.851+0000] {standard_task_runner.py:83} INFO - Job 348: Subtask insert_data
[2024-09-15T08:13:44.928+0000] {task_command.py:389} INFO - Running <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-15T07:33:25.648343+00:00 [running]> on host 0c5fe11d0c9c
[2024-09-15T08:13:45.061+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=save_city_info_weather_v01
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-09-15T07:33:25.648343+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-15T07:33:25.648343+00:00
[2024-09-15T08:13:45.063+0000] {sql.py:253} INFO - Executing: insert into weathers (city_name, max_temp, min_temp, wind, descript)
            values (
                     'Москва',
                     '21.29',
                     '19.1',
                     '3.52',
                     'облачно с прояснениями'); 
[2024-09-15T08:13:45.071+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-15T08:13:45.221+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-15T08:13:45.247+0000] {sql.py:364} INFO - Running statement: insert into weathers (city_name, max_temp, min_temp, wind, descript)
            values (
                     'Москва',
                     '21.29',
                     '19.1',
                     '3.52',
                     'облачно с прояснениями'); , parameters: None
[2024-09-15T08:13:45.251+0000] {sql.py:373} INFO - Rows affected: 1
[2024-09-15T08:13:45.260+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=save_city_info_weather_v01, task_id=insert_data, execution_date=20240915T073325, start_date=20240915T081344, end_date=20240915T081345
[2024-09-15T08:13:45.279+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-09-15T08:13:45.295+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
