[2024-09-14T19:15:48.722+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-14T18:27:08.114068+00:00 [queued]>
[2024-09-14T19:15:48.731+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-14T18:27:08.114068+00:00 [queued]>
[2024-09-14T19:15:48.733+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T19:15:48.737+0000] {taskinstance.py:1284} INFO - Starting attempt 6 of 6
[2024-09-14T19:15:48.737+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T19:15:48.748+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-09-14 18:27:08.114068+00:00
[2024-09-14T19:15:48.755+0000] {standard_task_runner.py:55} INFO - Started process 8500 to run task
[2024-09-14T19:15:48.765+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'save_city_info_weather_v01', 'insert_data', 'manual__2024-09-14T18:27:08.114068+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/saver_info.py', '--cfg-path', '/tmp/tmpkktv2ws6']
[2024-09-14T19:15:48.767+0000] {standard_task_runner.py:83} INFO - Job 95: Subtask insert_data
[2024-09-14T19:15:48.892+0000] {task_command.py:389} INFO - Running <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-14T18:27:08.114068+00:00 [running]> on host 0c5fe11d0c9c
[2024-09-14T19:15:49.038+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=save_city_info_weather_v01
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-09-14T18:27:08.114068+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-14T18:27:08.114068+00:00
[2024-09-14T19:15:49.040+0000] {sql.py:253} INFO - Executing: 
            insert into weathers (id, city_name, max_temp, min_temp, wind, description) values (1,ti.xcom_pull(task_ids="fetcher_data", key="return_value"), '10', '6', '2', 'Kakto')
        
[2024-09-14T19:15:49.059+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-14T19:15:49.181+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-14T19:15:49.186+0000] {sql.py:364} INFO - Running statement: 
            insert into weathers (id, city_name, max_temp, min_temp, wind, description) values (1,ti.xcom_pull(task_ids="fetcher_data", key="return_value"), '10', '6', '2', 'Kakto')
        , parameters: None
[2024-09-14T19:15:49.188+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "task_ids" does not exist
LINE 2: ...n_temp, wind, description) values (1,ti.xcom_pull(task_ids="...
                                                             ^

[2024-09-14T19:15:49.193+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=save_city_info_weather_v01, task_id=insert_data, execution_date=20240914T182708, start_date=20240914T191548, end_date=20240914T191549
[2024-09-14T19:15:49.200+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 95 for task insert_data (column "task_ids" does not exist
LINE 2: ...n_temp, wind, description) values (1,ti.xcom_pull(task_ids="...
                                                             ^
; 8500)
[2024-09-14T19:15:49.231+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-14T19:15:49.274+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
